name: 'Terraform CD'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform-CD'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      # Azure Login (using Service Principal)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq
        run: sudo apt-get install jq

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Download the tfplan from Azure Blob Storage
      - name: Download Plan from Azure Blob Storage
        run: |
          # Decode the secret JSON and extract individual values
          AZURE_STORAGE_ACCOUNT_NAME=$(echo "${{ secrets.AZURE_STORAGE_CREDENTIALS }}" | jq -r .AZURE_STORAGE_ACCOUNT_NAME)
          AZURE_STORAGE_CONTAINER_NAME=$(echo "${{ secrets.AZURE_STORAGE_CREDENTIALS }}" | jq -r .AZURE_STORAGE_CONTAINER_NAME)
          AZURE_STORAGE_ACCOUNT_KEY=$(echo "${{ secrets.AZURE_STORAGE_CREDENTIALS }}" | jq -r .AZURE_STORAGE_ACCOUNT_KEY)

          # Download the tfplan file from Azure Blob Storage
          az storage blob download \
            --account-name $AZURE_STORAGE_ACCOUNT_NAME \
            --container-name $AZURE_STORAGE_CONTAINER_NAME \
            --name tfplan \
            --file tfplan \
            --auth-mode key \
            --account-key $AZURE_STORAGE_ACCOUNT_KEY

      # Apply the tfplan to the infrastructure
      - name: Terraform Apply
        run: terraform apply --auto-approve tfplan
