name: 'Terraform CD'

on:
  workflow_run:
    workflows: ["Terraform CI"] # Name of the workflow to monitor
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform-CD'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      # Azure Login (using Service Principal)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:        
          name: terraform-plan
          path: /home/runner/work/Terraform_Pipeline/Terraform_Pipeline/artifacts

      # Check if artifact exists after download
      - name: Verify artifact location
        run: |
          ls -l /home/runner/work/Terraform_Pipeline/Terraform_Pipeline/artifacts
 
      # Check if the tfplan file exists
      - name: Check tfplan file existence
        run: |
          if [ ! -f /home/runner/work/Terraform_Pipeline/Terraform_Pipeline/artifacts/tfplan.out ]; then
            echo "tfplan.out not found!";
            exit 1;
          else
            echo "tfplan.out found!";
          fi

      
      - name: List files
        run: ls -R


      # Apply the tfplan to the infrastructure
      - name: Terraform Apply
        run: terraform apply --auto-approve artifacts/tfplan.out
