name: 'Terraform CI'

on:
  push:
    branches:
      - main 

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform-ci'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    # Azure Login (using Service Principal)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install jq
      run: sudo apt-get install jq


    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Check Terraform format
    - name: Terraform Format
      run: terraform fmt -check

    # Run Terraform Plan
    - name: Terraform Plan
      env:
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
      run: terraform plan -out=tfplan.out -input=false

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan.out
        path: .

    # Upload the tfplan file to Azure Blob Storage
    # - name: Upload Plan to Azure Blob Storage
    #   run: |
    #     # Decode the secret JSON and extract individual values
    #     AZURE_STORAGE_ACCOUNT_NAME=$(echo "${{ secrets.AZURE_STORAGE_CREDENTIALS }}" | jq -r .AZURE_STORAGE_ACCOUNT_NAME)
    #     AZURE_STORAGE_CONTAINER_NAME=$(echo "${{ secrets.AZURE_STORAGE_CREDENTIALS }}" | jq -r .AZURE_STORAGE_CONTAINER_NAME)
    #     AZURE_STORAGE_ACCOUNT_KEY=$(echo "${{ secrets.AZURE_STORAGE_CREDENTIALS }}" | jq -r .AZURE_STORAGE_ACCOUNT_KEY)

    #     # Upload the tfplan file to the Azure Blob Storage
    #     az storage blob upload \
    #       --account-name $AZURE_STORAGE_ACCOUNT_NAME \
    #       --container-name $AZURE_STORAGE_CONTAINER_NAME \
    #       --name tfplan \
    #       --file tfplan \
    #       --auth-mode key \
    #       --account-key $AZURE_STORAGE_ACCOUNT_KEY

    # # Optional: Upload the Plan as an artifact for further steps or debugging
    # - name: Upload Plan as Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: tfplan
    #     path: tfplan
